version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-coolify
      args:
        # Pass SESSION_SECRET as a build argument
        - SESSION_SECRET=${SESSION_SECRET}
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - PORT=5173
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HuggingFace_API_KEY=${HuggingFace_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      - XAI_API_KEY=${XAI_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - TOGETHER_API_BASE_URL=${TOGETHER_API_BASE_URL}
      - AWS_BEDROCK_CONFIG=${AWS_BEDROCK_CONFIG}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - DATABASE_URL=${DATABASE_URL}
      # Pass SESSION_SECRET as an environment variable as well
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      # Optional volume to persist .env.local across container restarts
      - ./bolt-env:/app/.env.local
    restart: unless-stopped
    # Ensure wrangler uses the correct command for Pages
    command: >
      sh -c "
        # Create .dev.vars for local development
        echo 'SESSION_SECRET=${SESSION_SECRET}' > .dev.vars && 
        # Start the application with Wrangler Pages
        pnpm run dockerstart
      "
    networks:
      - shared

networks:
  shared:
    external: true

volumes:
  bolt-env:
    driver: local