#~/wrangler.toml
#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"
send_metrics = false

# Define vars without the ${env.} syntax to allow environment variables to be used
[vars]
# Leave these empty to use the environment variables at runtime
SUPABASE_SERVICE_KEY = ""
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
SESSION_SECRET = ""

# Same for production environment
[env.production.vars]
SUPABASE_SERVICE_KEY = ""
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
SESSION_SECRET = ""
